// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedRackGroupMember type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedRackGroupMember{}

// ExpectedRackGroupMember External device identity; the case-sensitive tuple (type, manufacturer, id) is unique within a group.
type ExpectedRackGroupMember struct {
	// Case-sensitive REST rack component type. NVSwitch maps to Switch in Core.
	Type string `json:"type"`
	// Non-blank manufacturer name.
	Manufacturer string `json:"manufacturer"`
	// Non-blank opaque external device inventory identifier.
	Id string `json:"id"`
}

type _ExpectedRackGroupMember ExpectedRackGroupMember

// NewExpectedRackGroupMember instantiates a new ExpectedRackGroupMember object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedRackGroupMember(type_ string, manufacturer string, id string) *ExpectedRackGroupMember {
	this := ExpectedRackGroupMember{}
	this.Type = type_
	this.Manufacturer = manufacturer
	this.Id = id
	return &this
}

// NewExpectedRackGroupMemberWithDefaults instantiates a new ExpectedRackGroupMember object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedRackGroupMemberWithDefaults() *ExpectedRackGroupMember {
	this := ExpectedRackGroupMember{}
	return &this
}

// GetType returns the Type field value
func (o *ExpectedRackGroupMember) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupMember) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ExpectedRackGroupMember) SetType(v string) {
	o.Type = v
}

// GetManufacturer returns the Manufacturer field value
func (o *ExpectedRackGroupMember) GetManufacturer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Manufacturer
}

// GetManufacturerOk returns a tuple with the Manufacturer field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupMember) GetManufacturerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Manufacturer, true
}

// SetManufacturer sets field value
func (o *ExpectedRackGroupMember) SetManufacturer(v string) {
	o.Manufacturer = v
}

// GetId returns the Id field value
func (o *ExpectedRackGroupMember) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupMember) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ExpectedRackGroupMember) SetId(v string) {
	o.Id = v
}

func (o ExpectedRackGroupMember) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedRackGroupMember) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["manufacturer"] = o.Manufacturer
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ExpectedRackGroupMember) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"manufacturer",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedRackGroupMember := _ExpectedRackGroupMember{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExpectedRackGroupMember)

	if err != nil {
		return err
	}

	*o = ExpectedRackGroupMember(varExpectedRackGroupMember)

	return err
}

type NullableExpectedRackGroupMember struct {
	value *ExpectedRackGroupMember
	isSet bool
}

func (v NullableExpectedRackGroupMember) Get() *ExpectedRackGroupMember {
	return v.value
}

func (v *NullableExpectedRackGroupMember) Set(val *ExpectedRackGroupMember) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedRackGroupMember) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedRackGroupMember) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedRackGroupMember(val *ExpectedRackGroupMember) *NullableExpectedRackGroupMember {
	return &NullableExpectedRackGroupMember{value: val, isSet: true}
}

func (v NullableExpectedRackGroupMember) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedRackGroupMember) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
