// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ExpectedRackGroupList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpectedRackGroupList{}

// ExpectedRackGroupList Replace-all request body for Expected Rack Groups. The `expectedRackGroups` array contains the full desired set of Expected Rack Groups for the Site identified by `siteId`. All entries must reference the same `siteId` as the top-level field, and `rackGroupId` values must be unique within the request. The array is required and must not be null; use an explicit empty array to clear all Expected Rack Groups for the Site.
type ExpectedRackGroupList struct {
	// ID of the Site whose Expected Rack Groups should be replaced
	SiteId string `json:"siteId"`
	// The full desired set of Expected Rack Groups for the Site. Every entry must reference the same `siteId` as the top-level field, and `rackGroupId` values must be unique within the request. Required and non-null. Use an explicit empty array to clear all Expected Rack Groups for the Site.
	ExpectedRackGroups []ExpectedRackGroupCreateRequest `json:"expectedRackGroups"`
}

type _ExpectedRackGroupList ExpectedRackGroupList

// NewExpectedRackGroupList instantiates a new ExpectedRackGroupList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpectedRackGroupList(siteId string, expectedRackGroups []ExpectedRackGroupCreateRequest) *ExpectedRackGroupList {
	this := ExpectedRackGroupList{}
	this.SiteId = siteId
	this.ExpectedRackGroups = expectedRackGroups
	return &this
}

// NewExpectedRackGroupListWithDefaults instantiates a new ExpectedRackGroupList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpectedRackGroupListWithDefaults() *ExpectedRackGroupList {
	this := ExpectedRackGroupList{}
	return &this
}

// GetSiteId returns the SiteId field value
func (o *ExpectedRackGroupList) GetSiteId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupList) GetSiteIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SiteId, true
}

// SetSiteId sets field value
func (o *ExpectedRackGroupList) SetSiteId(v string) {
	o.SiteId = v
}

// GetExpectedRackGroups returns the ExpectedRackGroups field value
func (o *ExpectedRackGroupList) GetExpectedRackGroups() []ExpectedRackGroupCreateRequest {
	if o == nil {
		var ret []ExpectedRackGroupCreateRequest
		return ret
	}

	return o.ExpectedRackGroups
}

// GetExpectedRackGroupsOk returns a tuple with the ExpectedRackGroups field value
// and a boolean to check if the value has been set.
func (o *ExpectedRackGroupList) GetExpectedRackGroupsOk() ([]ExpectedRackGroupCreateRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedRackGroups, true
}

// SetExpectedRackGroups sets field value
func (o *ExpectedRackGroupList) SetExpectedRackGroups(v []ExpectedRackGroupCreateRequest) {
	o.ExpectedRackGroups = v
}

func (o ExpectedRackGroupList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpectedRackGroupList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["siteId"] = o.SiteId
	toSerialize["expectedRackGroups"] = o.ExpectedRackGroups
	return toSerialize, nil
}

func (o *ExpectedRackGroupList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"siteId",
		"expectedRackGroups",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExpectedRackGroupList := _ExpectedRackGroupList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varExpectedRackGroupList)

	if err != nil {
		return err
	}

	*o = ExpectedRackGroupList(varExpectedRackGroupList)

	return err
}

type NullableExpectedRackGroupList struct {
	value *ExpectedRackGroupList
	isSet bool
}

func (v NullableExpectedRackGroupList) Get() *ExpectedRackGroupList {
	return v.value
}

func (v *NullableExpectedRackGroupList) Set(val *ExpectedRackGroupList) {
	v.value = val
	v.isSet = true
}

func (v NullableExpectedRackGroupList) IsSet() bool {
	return v.isSet
}

func (v *NullableExpectedRackGroupList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpectedRackGroupList(val *ExpectedRackGroupList) *NullableExpectedRackGroupList {
	return &NullableExpectedRackGroupList{value: val, isSet: true}
}

func (v NullableExpectedRackGroupList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpectedRackGroupList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
